filebeat.inputs:
  - type: filestream
    id: microservices
    enabled: true
    paths:
      - /usr/share/filebeat/input-logs/*.log
    multiline.pattern: '^\s*trace_id:'
    multiline.negate: true
    multiline.match: after

    processors:
      # Extract service name from full filename
      - script:
          lang: javascript
          source: >
            function process(event) {
              var filePath = event.Get("log.file.path");
              if (filePath) {
                var fileName = filePath.split("/").pop();
                var baseName = fileName.replace(/\.log$/, "");
                event.Put("service.name", baseName);
              }
            }

      - dissect:
          tokenizer: 'trace_id: %{trace_id} | span_id: %{span_id} | %{log_date} %{log_time} [%{thread}] %{log.level} %{logger} - %{log.message}'
          field: "message"
          ignore_failure: true

      - drop_fields: 
          fields: ["log.file.path", "input.type"]
          ignore_missing: true

# Template setup - Use ONLY the setup section
setup.template.enabled: true
setup.template.name: "starline"
setup.template.pattern: "starline-*"
setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 0

# Disable ILM since you're using custom index names
setup.ilm.enabled: false

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "starline-%{[service.name]}"
  username: "${ELASTICSEARCH_USERNAME}"
  password: "${ELASTICSEARCH_PASSWORD}"
  # Remove template settings from here - they belong in setup section

setup.kibana:
  host: "kibana:5601"
  username: "${ELASTICSEARCH_USERNAME}"
  password: "${ELASTICSEARCH_PASSWORD}"

# Enhanced logging for debugging
logging.level: info
logging.to_stderr: true