filebeat.inputs:
  - type: filestream
    id: microservices
    enabled: true
    paths:
      - /usr/share/filebeat/input-logs/*.log

    parsers:
      - multiline:
          type: pattern
          pattern: '^\[trace_id:'
          negate: true
          match: after

    processors:
      - script:
          lang: javascript
          source: >
            function process(event) {
              var filePath = event.Get("log.file.path");
              if (filePath) {
                var fileName = filePath.split("/").pop();
                if (fileName) {
                  var baseName = fileName.replace(/\.log(\.gz)?$/, "");
                  event.Put("service.name", baseName);
                }
              }
            }
      
      - dissect:
          tokenizer: '[trace_id: %{trace_id}, span_id: %{span_id}] %{timestamp->} %{log.level->} %{pid} --- [%{thread}] %{logger->} : %{log.message}'
          field: "message"
          ignore_failure: true
      
      - dissect:
          tokenizer: '%{request_info} | %{trace_id_repeat} | RESPONSE: %{response_json}'
          field: "log.message"
          ignore_failure: true
      
      - decode_json_fields:
          fields: ["response_json"]
          target: "response"
          overwrite_keys: true
          add_error_key: false
          process_array: false
      
      - rename:
          fields:
            - from: "response.responseCode"
              to: "responseCode"
          ignore_missing: true
          fail_on_error: false
      
      - drop_fields:
          fields: ["log.file.path", "input.type", "response_json"]
          ignore_missing: true

# Template setup
setup.template.enabled: true
setup.template.name: "microservices"
setup.template.pattern: "microservices-*"
setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 0

# Disable ILM
setup.ilm.enabled: false

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "starline-%{[service.name]}"
  username: "${ELASTICSEARCH_USERNAME}"
  password: "${ELASTICSEARCH_PASSWORD}"

setup.kibana:
  host: "kibana:5601"
  username: "${ELASTICSEARCH_USERNAME}"
  password: "${ELASTICSEARCH_PASSWORD}"

# Logging
logging.level: info
logging.to_stderr: true